# https://taskfile.dev

version: '3'

tasks:
  build:
   desc: Build the NixOS configuration for the current host
   cmds:
      - nixos-rebuild build --flake .#${HOSTNAME} --show-trace
  lint:
    desc: Lint the files
    cmds:
      - bash -c "shopt -s globstar && nixfmt **/*.nix"
  switch:
    desc: Switch to the NixOS configuration for the current host
    cmds:
      - sudo nixos-rebuild switch --flake .#${HOSTNAME} --show-trace
  boot:
    desc: Set new configuration for next boot
    cmds:
      - sudo nixos-rebuild boot --flake .#${HOSTNAME} --show-trace
  update:
    desc: Update dependencies and lock file
    cmds:
      - nix flake update
