---
galaxy_info:
  author: kedare
  description: NVIDIA GPU driver configuration
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - noble  # 24.04

dependencies: []
