---
- name: Enable 32-bit architecture (for Steam)
  ansible.builtin.command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch
  register: enable_i386

- name: Update apt cache after enabling i386
  ansible.builtin.apt:
    update_cache: true
  when: enable_i386.changed

- name: Install 32-bit graphics libraries
  ansible.builtin.apt:
    name:
      - libgl1-mesa-dri:i386
      - libgl1:i386
      - libgl1-mesa-glx:i386
    state: present

- name: Add multiverse repository (for Steam)
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
    state: present

- name: Install Steam
  ansible.builtin.apt:
    name: steam
    state: present
    update_cache: true

- name: Configure UFW rules for Steam
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop:
    - { port: "27036", proto: "tcp", comment: "Steam Remote Play" }
    - { port: "27037", proto: "tcp", comment: "Steam Remote Play" }
    - { port: "27031-27036", proto: "udp", comment: "Steam Remote Play" }
  when: ufw_enabled | default(true)

- name: Install Heroic Games Launcher via Flatpak
  block:
    - name: Install Flatpak
      ansible.builtin.apt:
        name: flatpak
        state: present

    - name: Add Flathub repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Heroic Games Launcher
      community.general.flatpak:
        name: com.heroicgameslauncher.hgl
        state: present
