---
galaxy_info:
  author: kedare
  description: Server-specific configuration (systemd-networkd)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - noble  # 24.04

dependencies: []
