---
- name: Enable IPv4 forwarding (for tailscale subnet routing)
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Enable IPv6 forwarding (for tailscale subnet routing)
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Disable IPv6 temporary addresses on servers
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "0"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv6.conf.all.use_tempaddr
    - net.ipv6.conf.default.use_tempaddr
  when: disable_ipv6_temp_addr | default(false)
