---
# Desktop machines configuration
- name: Configure desktop machines
  hosts: desktops
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: [common, base]

    - role: desktop
      tags: [desktop, gnome]

    - role: monitoring
      tags: [monitoring]

  tasks:
    - name: Apply development environment role
      ansible.builtin.include_role:
        name: devenv
      when: "'devenv' in enabled_roles | default([])"
      tags: [devenv]

    - name: Apply gaming role
      ansible.builtin.include_role:
        name: gaming
      when: "'gaming' in enabled_roles | default([])"
      tags: [gaming]

    - name: Apply AMD GPU role
      ansible.builtin.include_role:
        name: gpu_amd
      when: "'amd_gpu' in group_names"
      tags: [gpu, amd]

    - name: Apply NVIDIA GPU role
      ansible.builtin.include_role:
        name: gpu_nvidia
      when: "'nvidia_gpu' in group_names"
      tags: [gpu, nvidia]

    - name: Apply Intel GPU role
      ansible.builtin.include_role:
        name: gpu_intel
      when: "'intel_gpu' in group_names"
      tags: [gpu, intel]

    - name: Apply HTPC role
      ansible.builtin.include_role:
        name: htpc
      when: "'htpc' in group_names"
      tags: [htpc, kodi]
